### ISSUE TITLE
install instructions require more clarity

### ISSUE THREAD

**Issue by devonorourke** [caporaso-lab/tax-credit-data#6]
I wasn't clear what the issue was when I was trying to install everything, but I think it's because a repo was renamed. 
See [this issue post](https://github.com/caporaso-lab/tax-credit-code/issues/4) to link it all together.

**Comment by nbokulich** [comment]
no that's all correct. You need to install `tax-credit-code` to use the notebooks in this repo.

However, you are correct that the install instructions should clarify that you also need to clone this repo! So:
```
git clone https://github.com/gregcaporaso/tax-credit-data.git
cd tax-credit-data
```

Will leave this issue open to get that added. Thanks!
